### ISSUE TITLE
Should readValues() be called after checking errors instead?

### ISSUE THREAD

**Issue by geekecom** [Migueel0/TempSensor#2]
https://github.com/Migueel0/TempSensor/blob/e886c47cb2033c1356ca7f93bdaa05bc770f5add/humidity_sensor/humidity_sensor.ino#L51C3-L51C3

**Comment by Migueel0** [comment]
No, because if you read values after checkErrors, when an sensor error apears, fixing it you're not reading correct values  to avoid the error because of the return statement.The loop starts with last NaN values and the code will be freezed.
